language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra

before_install:
  - yes | sdkmanager "platforms;android-23"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master