sudo: false
language: android
jdk: oraclejdk8

android:
  components:
  - build-tools-27.0.3
  - android-27
  - extra

notifications:
  email: true

env:
  global:
  - secure: "uANLNxMW8F+EMwYKoqdslChfH2sQtpnQyl3kuNjsX6HJtGpsoKA1s4KP26w7DYlfM/l/UiZxuEmyxagRJoB0qGtTbO7m1W3lGf8OuXU1LSrMZfBvuzlqbEr9eqbP4lJzve3xv+sfWpCgYYZWeUt84RqkbuujPC9jHGwqSOzBcWpLjDBr/CkwO/ZeArtgi0jb3TciFGXS0CPWkNFXAJiABx4spYRU5eCraROPzVhLg/KLd53XONDdREzug9OQuCIKPKbd+qUnayFcao9HV+jH4RFSiz09W0ydhBxZkuMYawpAB2jNPvby0V3JYivVxJH8kdEQUqUG3Sj6vDZCdrHL73eEZcnXSeQrWofkNwp5mJ3ES9zMrcK72Q/zW8eXFdazsIKZGvt12bw57SplnUz1557vYywB4rgXFWBqPVK7chprW2vdMw4bFXCkqejwI/YB3eqSC9L3cSnlzAsFcntK1TDcMzelBwcf8KPDYHFNqwS8uPj8VIFYkYN91JMfjIFVVUoa/NJ9xnKHsZAE5o+HNjpFQcHatnJKqlRcmxXVEG2JAFlAcr+toKVhcm4UdfIv9f21W/r8hlh3zpWF3PH2D9qTMpENQMmKwRVavv4Net+xBDN7oie7MiFnCsI+wtIzbcj70gMFVFaas37VVWpcp4TyLHRaZvTMd4H2ciDyzaM="
  - secure: "Ios6osi8Th4Jo5jpbZt/qnrp3Koo6saLItFjKEGgqdZn3ThpEJ+uhu24Tc1zwY8ZbNRAL8pbL89wQHf6kriM925cFFbFHChU/N6RaadT/eRMoBGIeBpqaVnoyn83tr6GrtLG6GuuHQnZu9Q8+SSGsMkEEWWZWl/8znF5A5cyGzfLpoh8wF4xhSh0Mj+gCoGH9Z+XP4NgB0juNlJRdjjD4igWvcNpaI41dCVQxE3hAhpShsiYs0z9xaTqWwpMlD6Y3epdVRzd7QeLYKgm5aCCFOJ/vwYtZiLbGDS//QUme1wSNbnUArz/IV4X3eJtG4ngBdvU/FDuzHTvApbY2LZSlEjRgdeW0TuzBKo/wdAT2Dvs9Yiz29dUv6o3aYqG1rlA5trT3NRW2kB1b9jV0cY+tTeH6wVleJlcRypLGg29usdqM8l+FUWzg7GtRVn+Uu3w4+5P9/eV+Yvr+fzHvQGZkNRzAxKOmqBwNP/dZhLjBSPQQ7P/JeMeVmaqAgF1GusA4puRqLgnhIu7DD94tvpQY/ydSGotqLX+kcQ2f2mUIs7vk6MgZTS/rjr8/9BPDyh93eLORDo5WUHZHgwR3/RFk/cTnMabYmFuu7aPwvdQMX3Ai2dcU7gB5zia41Uc3HgIWV74+g1oPeVPyB4sw3Ehdn2ytKPb6P7NuGxd0Od/3ZI="

before_install:
  - yes | sdkmanager "platforms;android-23"
  - openssl aes-256-cbc -K $encrypted_72ad576912f2_key -iv $encrypted_72ad576912f2_iv -in android_ks.jks.enc -out android_ks.jks -d

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

before_deploy:
  - cp $TRAVIS_BUILD_DIR/android_ks.jks $HOME
  - cd HomeCloud/build/outputs/apk/release/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "${HOME}/android_ks.jks" -storepass ${storepass} -keypass ${keypass} HomeCloud-release-unsigned.apk homecloudws

# Verification
  - jarsigner -verify HomeCloud-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/27.0.3/zipalign -v 4 HomeCloud-release-unsigned.apk HomeCloudWS.apk"

deploy:
  provider: releases
  api_key:
    secure: X7POt1oc4VeEHk+pNfl0DDDy1+rkle5EZs0d4V34rFOlbTyHsu3G0fDG3RqHokm0pk6xdlyvPwyV1BkUchlssbtcV2GAu4iYrvZomLfhow9NUmEOYaiWrX7p86VP2dwokp6tJaOkca6NrTifAQSbr3jEutdlVK3Sl14+MVGH8rCVlBy69Cw6nPUsN3MeR083q5HCTtZrwq+K4HUxfRtLbxdAf8DZW1kAQ9q6T3LHEuuuNwCcD+Cg0jIX3ymDC8Ei9lRmKpRHaBtwt264IdTjXrPX50ssHRSqF4ZpSSMbpyFjTut4VnuT3/9vzK5P267L3sQmmBhCP+ihAeTjm/E8FJxn9n8nfCrOoK5rv4yxyWP8n1RGz1ikHAbEzkaef0HVN5F5Vs97APZhyOhKQzeXb1xHRhCHlavnRkJZ2SQ2f6CiAnY5mxusErpCzu4mis35A2G1SyEiGQYz5MEWmFbO8uipQHMMBOwBlqssfz0BVC9Y/SRnd4nTPaGRcVE2tp1w6EZclGot/7x77y+amC1e49qaTVsGQs4+y55NBfYeEWoZgKiHJ+V1pN4WkmnU8488o2DeowbDjeJSC2Hu3SgapmqHYVrD4WMcVOsXCoZ46F8I6V5WdQDka+6rJYWZzJj4q8Fe/GWz6g+IYjsp7e5GLOMx/u21N9y9lXC4Nh1cf70=
  file: HomeCloud/build/outputs/apk/release/HomeCloud*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: pablo-dev/HomeCloudAndroidWS

after_success:
  - sh set_tags.sh